"""Compatibility facade for JSON-friendly application serializers."""

from __future__ import annotations

from application.shared.serializer_parts.agent import (
    serialize_agent_runtime_action,
    serialize_agent_runtime_action_execution,
    serialize_agent_runtime_artifact,
    serialize_agent_runtime_step,
    serialize_agent_runtime_task_plan,
    serialize_agent_runtime_task_plan_entry,
)
from application.shared.serializer_parts.core import (
    serialize_agent_run_history_entry,
    serialize_answer_bundle,
    serialize_benchmark_run_history_entry,
    serialize_directory_analysis_node_stat,
    serialize_directory_analysis_report,
    serialize_directory_coverage_suggestion,
    serialize_generated_answer,
    serialize_note,
    serialize_query_history_entry,
    serialize_retrieval_bundle,
    serialize_retrieved_note,
)
from application.shared.serializer_parts.notes import (
    serialize_applied_note_change,
    serialize_generated_note_draft,
    serialize_maintenance_draft_plan,
    serialize_maintenance_draft_plan_entry,
    serialize_maintenance_finding,
    serialize_maintenance_plan,
    serialize_maintenance_plan_entry,
    serialize_maintenance_report,
    serialize_note_change_proposal,
)
from application.shared.serializer_parts.training import (
    serialize_prompt_patch_plan,
    serialize_prompt_patch_suggestion,
    serialize_training_corpus,
    serialize_training_evaluation_comparison,
    serialize_training_evaluation_example_result,
    serialize_training_evaluation_failure_snapshot,
    serialize_training_evaluation_leaderboard,
    serialize_training_evaluation_leaderboard_entry,
    serialize_training_evaluation_report,
    serialize_training_example,
    serialize_training_fine_tune_bundle,
    serialize_training_fine_tune_recipe,
    serialize_training_manifest,
    serialize_training_optimizer_leaderboard,
    serialize_training_optimizer_leaderboard_entry,
    serialize_training_optimizer_sweep_report,
    serialize_training_split,
    serialize_training_trainer_artifact,
)

__all__ = [
    "serialize_agent_run_history_entry",
    "serialize_agent_runtime_action",
    "serialize_agent_runtime_action_execution",
    "serialize_agent_runtime_artifact",
    "serialize_agent_runtime_step",
    "serialize_agent_runtime_task_plan",
    "serialize_agent_runtime_task_plan_entry",
    "serialize_answer_bundle",
    "serialize_applied_note_change",
    "serialize_benchmark_run_history_entry",
    "serialize_directory_analysis_node_stat",
    "serialize_directory_analysis_report",
    "serialize_directory_coverage_suggestion",
    "serialize_generated_answer",
    "serialize_generated_note_draft",
    "serialize_maintenance_draft_plan",
    "serialize_maintenance_draft_plan_entry",
    "serialize_maintenance_finding",
    "serialize_maintenance_plan",
    "serialize_maintenance_plan_entry",
    "serialize_maintenance_report",
    "serialize_note",
    "serialize_note_change_proposal",
    "serialize_prompt_patch_plan",
    "serialize_prompt_patch_suggestion",
    "serialize_query_history_entry",
    "serialize_retrieval_bundle",
    "serialize_retrieved_note",
    "serialize_training_corpus",
    "serialize_training_evaluation_comparison",
    "serialize_training_evaluation_example_result",
    "serialize_training_evaluation_failure_snapshot",
    "serialize_training_evaluation_leaderboard",
    "serialize_training_evaluation_leaderboard_entry",
    "serialize_training_evaluation_report",
    "serialize_training_example",
    "serialize_training_fine_tune_bundle",
    "serialize_training_fine_tune_recipe",
    "serialize_training_manifest",
    "serialize_training_optimizer_leaderboard",
    "serialize_training_optimizer_leaderboard_entry",
    "serialize_training_optimizer_sweep_report",
    "serialize_training_split",
    "serialize_training_trainer_artifact",
]
